TecnoClick/Blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name=('Blog')),
    path('categoria/<int:categoria_id>/', views.categoria, name="Categoria")
]

TecnoClick/Carrito/urls.py
from django.urls import path
from . import views

app_name = "Carrito"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.post_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.delete_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

TecnoClick/TecnoClick/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('service/', include('Servicios.urls')),
    path('about/', include('Blog.urls')),
    path('contact/', include('Contacto.urls')),
    path('store/', include('Tienda.urls')),
    path('Carrito/', include('Carrito.urls')),
    path('Autenticacion/', include('Autenticacion.urls')),
    path('Pedidos/', include('Pedidos.urls')),
    path('', include('TecnoClickApp.urls')),
]

TecnoClick/Tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name="Tienda"),

]

TecnoClick/Tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    Nombre = models.CharField(max_length=50)
    Created = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="CategoriaProd"
        verbose_name_plural="CategoriasProd"

    def __str__(self):
        return self.Nombre
    
class Producto(models.Model):
    Nombre = models.CharField(max_length=50)
    Categoria = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    Imagen = models.ImageField(upload_to="img_productos", null=True, blank=True)
    Precio = models.FloatField()
    Disponibilidad = models.BooleanField(default=True)
    Created = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

TecnoClick/Tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.
def tienda (request):

    productos = Producto.objects.all()

    return render(request, "Tienda/store.html", {"productos": productos})

TecnoClick/Tienda/templates/Carro/widget.html
<table class="table table-bordered table-dark table-hover rounded shadow-sm">
    <thead class="thead-dark text-center">
        <tr>
            <th colspan="3" class="text-center fs-4">
                🛒 Carro de Compras
            </th>
        </tr>
        <tr>
            <th class="text-uppercase">Producto</th>
            <th class="text-uppercase">Cantidad</th>
            <th class="text-uppercase">Acciones / Suma</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.Carrito.items %}
            {% for key, value in request.session.Carrito.items %}
            <tr>
                <td class="align-middle">{{ value.Nombre }}</td>
                <td class="align-middle">{{ value.Cantidad }}</td>
                <td class="align-middle">
                    <div class="d-flex gap-2 justify-content-center mb-1">
                        <a href="{% url 'Carrito:agregar' value.producto_id %}" class="btn btn-sm btn-success" title="Agregar uno">+</a>
                        <a href="{% url 'Carrito:restar' value.producto_id %}" class="btn btn-sm btn-secondary" title="Restar uno">-</a>
                    </div>
                    <div class="text-center">
                        ${{ value.Precio }}
                    </div>
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center mb-0">
                        🚫 Sin productos en el carrito
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr class="bg-secondary text-white">
            <td colspan="3" class="text-end fw-bold">
                Total: ${{ importe_total_carro }}
            </td>
        </tr>
        {% if request.session.Carrito.items %}
        <tr>
            <td colspan="3" style="text-align: center;">
                <a href="{% url 'ProcesarPedido' %}" class="btn btn-primary">Pedir</a>
            </td>
        </tr>
        {% endif %}
    </tfoot>
</table>